name: zeta_example
description: Demonstrates how to use zeta
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.6.0
  flutter: ^3.27.0

resolution: workspace

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  path_drawing: ^1.0.1
  zeta_flutter:
    path: ../packages/zeta_flutter

flutter:
  uses-material-design: true
