name: zeta_example
description: Demonstrates how to use zeta
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  go_router: ^14.1.2
  path_drawing: ^1.0.1
  zeta_flutter:
    path: ../

dev_dependencies:
  zds_analysis: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
