name: zeta_example
description: Demonstrates how to use zeta
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^11.1.2
  google_fonts: ^6.1.0
  zeta_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  widgetbook: ^3.1.0

flutter:
  uses-material-design: true
