name: zeta_example
description: Demonstrates how to use zeta
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^3.0.5
  google_fonts: ^4.0.3
  widgetbook: ^2.4.1
  widgetbook_models: ^0.0.7
  zeta_flutter:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
