include: all_lint_rules.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    included_file_warning: ignore
    missing_required_param: error
    missing_return: error
    deprecated_member_use_from_same_package: ignore
    parameter_assignments: warning

linter:
  rules:
    always_put_control_body_on_new_line: false
    always_put_required_named_parameters_first: false
    always_specify_types: false
    always_use_package_imports: false
    avoid_classes_with_only_static_members: false
    avoid_positional_boolean_parameters: false
    avoid_types_on_closure_parameters: false
    cascade_invocations: false
    close_sinks: false
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
    prefer_constructors_over_static_methods: false
    prefer_double_quotes: false
    prefer_expression_function_bodies: false
    prefer_final_parameters: false
    prefer_int_literals: false
    sort_constructors_first: false
    unnecessary_final: false
