name: zeta_flutter

packages:
  - packages/**
  - example/*
  - widgetbook/*

command:
  publish:
    hooks:
      pre: sh scripts/pre-publish.sh

scripts:
  analyze:
    exec: dart analyze .
  fix:
    exec: dart fix --apply
  cp-changelog:
    exec: cp ../../CHANGELOG.md .
