name: zeta_flutter_workspace

packages:
  - packages/**
  - example/*
  - widgetbook/*

command:
  publish:
    hooks:
      pre: |
        dart format packages --fix
        dart fix --apply

scripts:
  doc: dart doc packages/zeta_flutter
  build_runner:
    exec: dart run build_runner build -d
  test:
    steps:
      - rm -rf .coverage
      - melos exec -- bash ../../scripts/cov_move.sh
      - bash scripts/lcov_combine.sh
  pana: melos exec -- bash ../../scripts/pana.sh
