name: zeta_flutter_workspace

packages:
  - packages/**
  - example/*
  - widgetbook/*

scripts:
  doc: dart doc packages/zeta_flutter
  build_runner:
    exec: dart run build_runner build -d
  test: |
    rm -rf .coverage
    melos exec -- sh ../../scripts/cov_move.sh
    sh scripts/lcov_combine.sh
