name: zeta_flutter_workspace

packages:
  - packages/**
  - example/*
  - widgetbook/*

command:
  publish:
    hooks:
      pre: |
        dart format packages --fix
        dart fix --apply

scripts:
  doc: dart doc packages/zeta_flutter
  build_runner:
    exec: dart run build_runner build -d
  test:
    run: rm -rf .coverage && melos test_individual && bash scripts/lcov_combine.sh

  test_individual:
    run: bash ../../scripts/cov_move.sh
    exec:
      failFast: true
      concurrency: 1

  pana: melos exec -- bash ../../scripts/pana.sh
