name: zeta_flutter_workspace

packages:
  - packages/**
  - example/*
  - widgetbook/*

scripts:
  analyze:
    exec: dart analyze .
  fix:
    exec: dart fix --apply
  build_runner:
    exec: dart run build_runner build -d
    # melos exec -- flutter test
  test: |
    rm -rf coverage
    melos exec -- sh ../../scripts/cov_move.sh
    sh scripts/lcov_combine.sh
