name: zeta_flutter

packages:
  - packages/**
  - example/*
  - widgetbook/*

scripts:
  analyze:
    exec: dart analyze .
  fix:
    exec: dart fix --apply

command:
  publish:
    hooks:
      pre: echo 'hi'
