name: zeta_flutter_workspace

packages:
  - packages/**
  - example/*
  - widgetbook/*

scripts:
  analyze:
    exec: dart analyze .
  fix:
    exec: dart fix --apply
  build_runner:
    exec: dart run build_runner build -d
  cp-changelog:
    exec: cp ../../CHANGELOG.md .
