// Mocks generated by Mockito 5.4.4 from annotations
// in zeta_flutter/test/src/utils/extensions_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i9;

import 'package:flutter/foundation.dart' as _i3;
import 'package:flutter/material.dart' as _i2;
import 'package:flutter/src/widgets/notification_listener.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:zeta_flutter/generated/generated.dart' as _i5;
import 'package:zeta_flutter/src/theme/color_scheme.dart' as _i7;
import 'package:zeta_flutter/src/theme/color_swatch.dart' as _i4;
import 'package:zeta_flutter/src/theme/contrast.dart' as _i10;
import 'package:zeta_flutter/zeta_flutter.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWidget_0 extends _i1.SmartFake implements _i2.Widget {
  _FakeWidget_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeInheritedWidget_1 extends _i1.SmartFake
    implements _i2.InheritedWidget {
  _FakeInheritedWidget_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_2 extends _i1.SmartFake
    implements _i3.DiagnosticsNode {
  _FakeDiagnosticsNode_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i3.TextTreeConfiguration? parentConfiguration,
    _i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info,
  }) =>
      super.toString();
}

class _FakeZetaColorSwatch_3 extends _i1.SmartFake
    implements _i4.ZetaColorSwatch {
  _FakeZetaColorSwatch_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeZetaSemanticBorderColors_4 extends _i1.SmartFake
    implements _i5.ZetaSemanticBorderColors {
  _FakeZetaSemanticBorderColors_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeZetaSemanticMainColors_5 extends _i1.SmartFake
    implements _i5.ZetaSemanticMainColors {
  _FakeZetaSemanticMainColors_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeZetaPrimitives_6 extends _i1.SmartFake
    implements _i5.ZetaPrimitives {
  _FakeZetaPrimitives_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeZetaSemanticStateColors_7 extends _i1.SmartFake
    implements _i5.ZetaSemanticStateColors {
  _FakeZetaSemanticStateColors_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeZetaSemanticSurfaceColors_8 extends _i1.SmartFake
    implements _i5.ZetaSemanticSurfaceColors {
  _FakeZetaSemanticSurfaceColors_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeZetaColors_9 extends _i1.SmartFake implements _i6.ZetaColors {
  _FakeZetaColors_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeZetaColorScheme_10 extends _i1.SmartFake
    implements _i7.ZetaColorScheme {
  _FakeZetaColorScheme_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeZetaSemanticColors_11 extends _i1.SmartFake
    implements _i5.ZetaSemanticColors {
  _FakeZetaSemanticColors_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeZetaSpacingSemantics_12 extends _i1.SmartFake
    implements _i5.ZetaSpacingSemantics {
  _FakeZetaSpacingSemantics_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeZetaRadiiSemantics_13 extends _i1.SmartFake
    implements _i5.ZetaRadiiSemantics {
  _FakeZetaRadiiSemantics_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInheritedElement_14 extends _i1.SmartFake
    implements _i2.InheritedElement {
  _FakeInheritedElement_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i2.BuildContext {
  @override
  _i2.Widget get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeWidget_0(
          this,
          Invocation.getter(#widget),
        ),
        returnValueForMissingStub: _FakeWidget_0(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i2.Widget);

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get debugDoingBuild => (super.noSuchMethod(
        Invocation.getter(#debugDoingBuild),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.InheritedWidget dependOnInheritedElement(
    _i2.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dependOnInheritedElement,
          [ancestor],
          {#aspect: aspect},
        ),
        returnValue: _FakeInheritedWidget_1(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
        returnValueForMissingStub: _FakeInheritedWidget_1(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
      ) as _i2.InheritedWidget);

  @override
  void visitAncestorElements(_i2.ConditionalElementVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitAncestorElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void visitChildElements(_i2.ElementVisitor? visitor) => super.noSuchMethod(
        Invocation.method(
          #visitChildElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispatchNotification(_i8.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(
          #dispatchNotification,
          [notification],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.DiagnosticsNode describeElement(
    String? name, {
    _i3.DiagnosticsTreeStyle? style = _i3.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeElement,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
      ) as _i3.DiagnosticsNode);

  @override
  _i3.DiagnosticsNode describeWidget(
    String? name, {
    _i3.DiagnosticsTreeStyle? style = _i3.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeWidget,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
      ) as _i3.DiagnosticsNode);

  @override
  List<_i3.DiagnosticsNode> describeMissingAncestor(
          {required Type? expectedAncestorType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeMissingAncestor,
          [],
          {#expectedAncestorType: expectedAncestorType},
        ),
        returnValue: <_i3.DiagnosticsNode>[],
        returnValueForMissingStub: <_i3.DiagnosticsNode>[],
      ) as List<_i3.DiagnosticsNode>);

  @override
  _i3.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeOwnershipChain,
          [name],
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
      ) as _i3.DiagnosticsNode);
}

/// A class which mocks [ZetaColors].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockZetaColors extends _i1.Mock implements _i6.ZetaColors {
  @override
  _i9.Brightness get brightness => (super.noSuchMethod(
        Invocation.getter(#brightness),
        returnValue: _i9.Brightness.dark,
        returnValueForMissingStub: _i9.Brightness.dark,
      ) as _i9.Brightness);

  @override
  _i10.ZetaContrast get contrast => (super.noSuchMethod(
        Invocation.getter(#contrast),
        returnValue: _i10.ZetaContrast.aa,
        returnValueForMissingStub: _i10.ZetaContrast.aa,
      ) as _i10.ZetaContrast);

  @override
  _i4.ZetaColorSwatch get primary => (super.noSuchMethod(
        Invocation.getter(#primary),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#primary),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#primary),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  _i4.ZetaColorSwatch get secondary => (super.noSuchMethod(
        Invocation.getter(#secondary),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#secondary),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#secondary),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  _i4.ZetaColorSwatch get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#error),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#error),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  _i4.ZetaColorSwatch get cool => (super.noSuchMethod(
        Invocation.getter(#cool),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#cool),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#cool),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  _i4.ZetaColorSwatch get warm => (super.noSuchMethod(
        Invocation.getter(#warm),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#warm),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#warm),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  _i4.ZetaColorSwatch get pure => (super.noSuchMethod(
        Invocation.getter(#pure),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#pure),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#pure),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  _i4.ZetaColorSwatch get blue => (super.noSuchMethod(
        Invocation.getter(#blue),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#blue),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#blue),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  _i4.ZetaColorSwatch get green => (super.noSuchMethod(
        Invocation.getter(#green),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#green),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#green),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  _i4.ZetaColorSwatch get red => (super.noSuchMethod(
        Invocation.getter(#red),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#red),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#red),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  _i4.ZetaColorSwatch get orange => (super.noSuchMethod(
        Invocation.getter(#orange),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#orange),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#orange),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  _i4.ZetaColorSwatch get purple => (super.noSuchMethod(
        Invocation.getter(#purple),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#purple),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#purple),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  _i4.ZetaColorSwatch get yellow => (super.noSuchMethod(
        Invocation.getter(#yellow),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#yellow),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#yellow),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  _i4.ZetaColorSwatch get teal => (super.noSuchMethod(
        Invocation.getter(#teal),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#teal),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#teal),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  _i4.ZetaColorSwatch get pink => (super.noSuchMethod(
        Invocation.getter(#pink),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#pink),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#pink),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  _i4.ZetaColorSwatch get surfaceAvatarGreen => (super.noSuchMethod(
        Invocation.getter(#surfaceAvatarGreen),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#surfaceAvatarGreen),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#surfaceAvatarGreen),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  _i4.ZetaColorSwatch get surfacePositive => (super.noSuchMethod(
        Invocation.getter(#surfacePositive),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#surfacePositive),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#surfacePositive),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  _i4.ZetaColorSwatch get surfaceWarning => (super.noSuchMethod(
        Invocation.getter(#surfaceWarning),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#surfaceWarning),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#surfaceWarning),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  _i4.ZetaColorSwatch get surfaceNegative => (super.noSuchMethod(
        Invocation.getter(#surfaceNegative),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#surfaceNegative),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#surfaceNegative),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  _i4.ZetaColorSwatch get surfaceInfo => (super.noSuchMethod(
        Invocation.getter(#surfaceInfo),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#surfaceInfo),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#surfaceInfo),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  _i4.ZetaColorSwatch get borderPrimaryMain => (super.noSuchMethod(
        Invocation.getter(#borderPrimaryMain),
        returnValue: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#borderPrimaryMain),
        ),
        returnValueForMissingStub: _FakeZetaColorSwatch_3(
          this,
          Invocation.getter(#borderPrimaryMain),
        ),
      ) as _i4.ZetaColorSwatch);

  @override
  bool get isDarkMode => (super.noSuchMethod(
        Invocation.getter(#isDarkMode),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
        returnValueForMissingStub: <Object?>[],
      ) as List<Object?>);

  @override
  _i5.ZetaSemanticBorderColors get border => (super.noSuchMethod(
        Invocation.getter(#border),
        returnValue: _FakeZetaSemanticBorderColors_4(
          this,
          Invocation.getter(#border),
        ),
        returnValueForMissingStub: _FakeZetaSemanticBorderColors_4(
          this,
          Invocation.getter(#border),
        ),
      ) as _i5.ZetaSemanticBorderColors);

  @override
  _i5.ZetaSemanticMainColors get main => (super.noSuchMethod(
        Invocation.getter(#main),
        returnValue: _FakeZetaSemanticMainColors_5(
          this,
          Invocation.getter(#main),
        ),
        returnValueForMissingStub: _FakeZetaSemanticMainColors_5(
          this,
          Invocation.getter(#main),
        ),
      ) as _i5.ZetaSemanticMainColors);

  @override
  _i5.ZetaPrimitives get primitives => (super.noSuchMethod(
        Invocation.getter(#primitives),
        returnValue: _FakeZetaPrimitives_6(
          this,
          Invocation.getter(#primitives),
        ),
        returnValueForMissingStub: _FakeZetaPrimitives_6(
          this,
          Invocation.getter(#primitives),
        ),
      ) as _i5.ZetaPrimitives);

  @override
  _i5.ZetaSemanticStateColors get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeZetaSemanticStateColors_7(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeZetaSemanticStateColors_7(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.ZetaSemanticStateColors);

  @override
  _i5.ZetaSemanticSurfaceColors get surface => (super.noSuchMethod(
        Invocation.getter(#surface),
        returnValue: _FakeZetaSemanticSurfaceColors_8(
          this,
          Invocation.getter(#surface),
        ),
        returnValueForMissingStub: _FakeZetaSemanticSurfaceColors_8(
          this,
          Invocation.getter(#surface),
        ),
      ) as _i5.ZetaSemanticSurfaceColors);

  @override
  _i6.ZetaColors copyWith({
    _i9.Brightness? brightness,
    _i10.ZetaContrast? contrast,
    _i4.ZetaColorSwatch? primary,
    _i4.ZetaColorSwatch? secondary,
    _i4.ZetaColorSwatch? error,
    _i4.ZetaColorSwatch? cool,
    _i4.ZetaColorSwatch? warm,
    dynamic white,
    dynamic black,
    dynamic surfacePrimary,
    dynamic surfaceSecondary,
    dynamic surfaceTertiary,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #brightness: brightness,
            #contrast: contrast,
            #primary: primary,
            #secondary: secondary,
            #error: error,
            #cool: cool,
            #warm: warm,
            #white: white,
            #black: black,
            #surfacePrimary: surfacePrimary,
            #surfaceSecondary: surfaceSecondary,
            #surfaceTertiary: surfaceTertiary,
          },
        ),
        returnValue: _FakeZetaColors_9(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #brightness: brightness,
              #contrast: contrast,
              #primary: primary,
              #secondary: secondary,
              #error: error,
              #cool: cool,
              #warm: warm,
              #white: white,
              #black: black,
              #surfacePrimary: surfacePrimary,
              #surfaceSecondary: surfaceSecondary,
              #surfaceTertiary: surfaceTertiary,
            },
          ),
        ),
        returnValueForMissingStub: _FakeZetaColors_9(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #brightness: brightness,
              #contrast: contrast,
              #primary: primary,
              #secondary: secondary,
              #error: error,
              #cool: cool,
              #warm: warm,
              #white: white,
              #black: black,
              #surfacePrimary: surfacePrimary,
              #surfaceSecondary: surfaceSecondary,
              #surfaceTertiary: surfaceTertiary,
            },
          ),
        ),
      ) as _i6.ZetaColors);

  @override
  _i6.ZetaColors apply({required _i10.ZetaContrast? contrast}) =>
      (super.noSuchMethod(
        Invocation.method(
          #apply,
          [],
          {#contrast: contrast},
        ),
        returnValue: _FakeZetaColors_9(
          this,
          Invocation.method(
            #apply,
            [],
            {#contrast: contrast},
          ),
        ),
        returnValueForMissingStub: _FakeZetaColors_9(
          this,
          Invocation.method(
            #apply,
            [],
            {#contrast: contrast},
          ),
        ),
      ) as _i6.ZetaColors);

  @override
  _i7.ZetaColorScheme toScheme() => (super.noSuchMethod(
        Invocation.method(
          #toScheme,
          [],
        ),
        returnValue: _FakeZetaColorScheme_10(
          this,
          Invocation.method(
            #toScheme,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeZetaColorScheme_10(
          this,
          Invocation.method(
            #toScheme,
            [],
          ),
        ),
      ) as _i7.ZetaColorScheme);
}

/// A class which mocks [Zeta].
///
/// See the documentation for Mockito's code generation for more information.
class MockZeta extends _i1.Mock implements _i6.Zeta {
  @override
  _i10.ZetaContrast get contrast => (super.noSuchMethod(
        Invocation.getter(#contrast),
        returnValue: _i10.ZetaContrast.aa,
        returnValueForMissingStub: _i10.ZetaContrast.aa,
      ) as _i10.ZetaContrast);

  @override
  _i2.ThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i2.ThemeMode.system,
        returnValueForMissingStub: _i2.ThemeMode.system,
      ) as _i2.ThemeMode);

  @override
  bool get rounded => (super.noSuchMethod(
        Invocation.getter(#rounded),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.ZetaSemanticColors get colors => (super.noSuchMethod(
        Invocation.getter(#colors),
        returnValue: _FakeZetaSemanticColors_11(
          this,
          Invocation.getter(#colors),
        ),
        returnValueForMissingStub: _FakeZetaSemanticColors_11(
          this,
          Invocation.getter(#colors),
        ),
      ) as _i5.ZetaSemanticColors);

  @override
  _i5.ZetaSpacingSemantics get spacing => (super.noSuchMethod(
        Invocation.getter(#spacing),
        returnValue: _FakeZetaSpacingSemantics_12(
          this,
          Invocation.getter(#spacing),
        ),
        returnValueForMissingStub: _FakeZetaSpacingSemantics_12(
          this,
          Invocation.getter(#spacing),
        ),
      ) as _i5.ZetaSpacingSemantics);

  @override
  _i5.ZetaRadiiSemantics get radii => (super.noSuchMethod(
        Invocation.getter(#radii),
        returnValue: _FakeZetaRadiiSemantics_13(
          this,
          Invocation.getter(#radii),
        ),
        returnValueForMissingStub: _FakeZetaRadiiSemantics_13(
          this,
          Invocation.getter(#radii),
        ),
      ) as _i5.ZetaRadiiSemantics);

  @override
  _i9.Brightness get brightness => (super.noSuchMethod(
        Invocation.getter(#brightness),
        returnValue: _i9.Brightness.dark,
        returnValueForMissingStub: _i9.Brightness.dark,
      ) as _i9.Brightness);

  @override
  _i2.Widget get child => (super.noSuchMethod(
        Invocation.getter(#child),
        returnValue: _FakeWidget_0(
          this,
          Invocation.getter(#child),
        ),
        returnValueForMissingStub: _FakeWidget_0(
          this,
          Invocation.getter(#child),
        ),
      ) as _i2.Widget);

  @override
  bool updateShouldNotify(_i2.InheritedWidget? oldWidget) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [oldWidget],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void debugFillProperties(_i3.DiagnosticPropertiesBuilder? properties) =>
      super.noSuchMethod(
        Invocation.method(
          #debugFillProperties,
          [properties],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.InheritedElement createElement() => (super.noSuchMethod(
        Invocation.method(
          #createElement,
          [],
        ),
        returnValue: _FakeInheritedElement_14(
          this,
          Invocation.method(
            #createElement,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeInheritedElement_14(
          this,
          Invocation.method(
            #createElement,
            [],
          ),
        ),
      ) as _i2.InheritedElement);

  @override
  String toStringShort() => (super.noSuchMethod(
        Invocation.method(
          #toStringShort,
          [],
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShort,
            [],
          ),
        ),
        returnValueForMissingStub: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShort,
            [],
          ),
        ),
      ) as String);

  @override
  String toStringShallow({
    String? joiner = r', ',
    _i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.debug,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toStringShallow,
          [],
          {
            #joiner: joiner,
            #minLevel: minLevel,
          },
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShallow,
            [],
            {
              #joiner: joiner,
              #minLevel: minLevel,
            },
          ),
        ),
        returnValueForMissingStub: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShallow,
            [],
            {
              #joiner: joiner,
              #minLevel: minLevel,
            },
          ),
        ),
      ) as String);

  @override
  String toStringDeep({
    String? prefixLineOne = r'',
    String? prefixOtherLines,
    _i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.debug,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toStringDeep,
          [],
          {
            #prefixLineOne: prefixLineOne,
            #prefixOtherLines: prefixOtherLines,
            #minLevel: minLevel,
          },
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #toStringDeep,
            [],
            {
              #prefixLineOne: prefixLineOne,
              #prefixOtherLines: prefixOtherLines,
              #minLevel: minLevel,
            },
          ),
        ),
        returnValueForMissingStub: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #toStringDeep,
            [],
            {
              #prefixLineOne: prefixLineOne,
              #prefixOtherLines: prefixOtherLines,
              #minLevel: minLevel,
            },
          ),
        ),
      ) as String);

  @override
  _i3.DiagnosticsNode toDiagnosticsNode({
    String? name,
    _i3.DiagnosticsTreeStyle? style,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toDiagnosticsNode,
          [],
          {
            #name: name,
            #style: style,
          },
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #toDiagnosticsNode,
            [],
            {
              #name: name,
              #style: style,
            },
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #toDiagnosticsNode,
            [],
            {
              #name: name,
              #style: style,
            },
          ),
        ),
      ) as _i3.DiagnosticsNode);

  @override
  List<_i3.DiagnosticsNode> debugDescribeChildren() => (super.noSuchMethod(
        Invocation.method(
          #debugDescribeChildren,
          [],
        ),
        returnValue: <_i3.DiagnosticsNode>[],
        returnValueForMissingStub: <_i3.DiagnosticsNode>[],
      ) as List<_i3.DiagnosticsNode>);

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}
