name: zeta_icons
description: "An icon library for the Zeta Design System by Zebra Technologies."
version: 1.0.0+-alpha.2
homepage: https://design.zebra.com
repository: https://github.com/zebradevs/zeta_flutter/tree/develop/packages/zeta_icons # TODO: Luke Update develop to main
issue_tracker: https://github.com/zebradevs/zeta_flutter/issues

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  zds_analysis: ^1.1.1

flutter:
  fonts:
    - family: zeta-icons
      fonts:
        - asset: assets/zeta-icons-round.ttf
    - family: zeta-icons-round
      fonts:
        - asset: assets/zeta-icons-round.ttf
    - family: zeta-icons-sharp
      fonts:
        - asset: assets/zeta-icons-sharp.ttf
