name: zeta_icons
description: "An icon library for the Zeta Design System by Zebra Technologies."
version: 1.1.7
homepage: https://design.zebra.com
repository: https://github.com/zebradevs/zeta_flutter/tree/main/packages/zeta_icons
issue_tracker: https://github.com/zebradevs/zeta_flutter/issues

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  zds_analysis: ^1.2.0

flutter:
  assets:
    - lib/assets/illustrations/zdna/
    - lib/assets/illustrations/workcloud/

  fonts:
    - family: zeta-icons
      fonts:
        - asset: lib/assets/icons/zeta-icons-round.ttf
    - family: zeta-icons-round
      fonts:
        - asset: lib/assets/icons/zeta-icons-round.ttf
    - family: zeta-icons-sharp
      fonts:
        - asset: lib/assets/icons/zeta-icons-sharp.ttf
  uses-material-design: true
