name: zeta_flutter_utils
description: "Utility functions for the Zeta Design System from Zebra Technologies."
version: 1.2.1
homepage: https://design.zebra.com
repository: https://github.com/zebradevs/zeta_flutter/tree/main/packages/zeta_flutter_utils
issue_tracker: https://github.com/zebradevs/zeta_flutter/issues

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.1

dev_dependencies:
  analyzer: ^7.4.5
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
  zds_analysis: ^1.2.0
  zeta_flutter:
    path: ../zeta_flutter

  zeta_flutter_theme: any
flutter:
  uses-material-design: true
