name: zeta_flutter_utils
description: "Utility functions for the Zeta Design System from Zebra Technologies."
version: 0.20.1
homepage: https://design.zebra.com
repository: https://github.com/zebradevs/zeta_flutter/tree/main/packages/zeta_flutter_utils
issue_tracker: https://github.com/zebradevs/zeta_flutter/issues

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.0

dev_dependencies:
  analyzer: ^7.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  zds_analysis: ^1.1.1
  zeta_flutter:
    path: ../zeta_flutter
  zeta_flutter_theme:
    path: ../zeta_flutter_theme
