name: zeta_flutter_utils
description: "Utility functions for the Zeta Design System."
version: 1.0.0-alpha.1
homepage: https://design.zebra.com
repository: https://github.com/ZebraDevs/zeta_flutter/packages/zeta_flutter
issue_tracker: https://github.com/zebradevs/zeta_flutter/issues
documentation: https://design.zebra.com/flutter/dartdoc/index.html

environment:
  sdk: ">=3.6.0"
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  analyzer: ^6.0.0
  flutter:
    sdk: flutter
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  zds_analysis: ^1.1.1
  zeta_flutter:
    path: ../zeta_flutter
