name: zeta_flutter_theme
description: "Theme resources for the Zeta Design System from Zebra Technologies."
version: 0.20.2
homepage: https://design.zebra.com
repository: https://github.com/zebradevs/zeta_flutter/tree/main/packages/zeta_flutter_theme
issue_tracker: https://github.com/zebradevs/zeta_flutter/issues

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  zds_analysis: ^1.1.1
  zeta_flutter: ^0.20.2

flutter:
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Light.otf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-Regular.otf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-Medium.otf
          weight: 500
