import 'package:flutter/material.dart';

import '../../zeta_flutter.dart';

/// Returns a ZetaIcon based on the file extension.
/// Returns null if no matching icon is found.
ZetaIcon? getFileExtensionIcon(String extension) {
  final ext = extension.toLowerCase();
  final iconData = _extensionIconMap[ext];
  return iconData != null ? ZetaIcon(iconData) : null;
}

const Map<String, IconData> _extensionIconMap = {
  'aac': ZetaIcons.aac_attach,
  'ai': ZetaIcons.ai_attach,
  'asp': ZetaIcons.asp_attach,
  '3ds': ZetaIcons.attach_3ds,
  'au': ZetaIcons.au_attach,
  'avi': ZetaIcons.avi_attach,
  'bin': ZetaIcons.bin_attach,
  'bmp': ZetaIcons.bmp_attach,
  'com': ZetaIcons.com_attach,
  'css': ZetaIcons.css_attach,
  'csv': ZetaIcons.csv_attach,
  'dat': ZetaIcons.dat_attach,
  'dbf': ZetaIcons.dbf_attach,
  'dll': ZetaIcons.dll_attach,
  'doc': ZetaIcons.doc_attach,
  'docx': ZetaIcons.docx_attach,
  'dwg': ZetaIcons.dwg_attach,
  'eml': ZetaIcons.eml_attach,
  'eps': ZetaIcons.eps_attach,
  'exe': ZetaIcons.exe_attach,
  'ext': ZetaIcons.ext_attach,
  'fla': ZetaIcons.fla_attach,
  'fodg': ZetaIcons.fodg_attach,
  'fodp': ZetaIcons.fodp_attach,
  'fods': ZetaIcons.fods_attach,
  'gif': ZetaIcons.gif_attach,
  'htm': ZetaIcons.htm_attach,
  'html': ZetaIcons.html_attach,
  'ico': ZetaIcons.ico_attach,
  'ini': ZetaIcons.ini_attach,
  'iso': ZetaIcons.iso_attach,
  'jar': ZetaIcons.jar_attach,
  'jpeg': ZetaIcons.jpeg_attach,
  'jpg': ZetaIcons.jpg_attach,
  'js': ZetaIcons.js_attach,
  'json': ZetaIcons.json_attach,
  'key': ZetaIcons.key_attach,
  'mdb': ZetaIcons.mdb_attach,
  'mkv': ZetaIcons.mkv_attach,
  'mov': ZetaIcons.mov_attach,
  'mp3': ZetaIcons.mp3_attach,
  'mp4': ZetaIcons.mp4_attach,
  'mpeg': ZetaIcons.mpeg_attach,
  'mpg': ZetaIcons.mpg_attach,
  'mpga': ZetaIcons.mpga_attach,
  'nfo': ZetaIcons.nfo_attach,
  'obj': ZetaIcons.obj_attach,
  'odf': ZetaIcons.odf_attach,
  'odp': ZetaIcons.odp_attach,
  'ods': ZetaIcons.ods_attach,
  'odt': ZetaIcons.odt_attach,
  'oog': ZetaIcons.oog_attach,
  'otf': ZetaIcons.otf_attach,
  'ott': ZetaIcons.ott_attach,
  'pdf': ZetaIcons.pdf_attach,
  'pkg': ZetaIcons.pkg_attach,
  'png': ZetaIcons.png_attach,
  'pps': ZetaIcons.pps_attach,
  'ppt': ZetaIcons.ppt_attach,
  'pptx': ZetaIcons.pptx_attach,
  'psd': ZetaIcons.psd_attach,
  'rar': ZetaIcons.rar_attach,
  'rtf': ZetaIcons.rtf_attach,
  'sdc': ZetaIcons.sdc_attach,
  'sdd': ZetaIcons.sdd_attach,
  'svg': ZetaIcons.svg_attach,
  'swf': ZetaIcons.swf_attach,
  'tif': ZetaIcons.tif_attach,
  'tiff': ZetaIcons.tiff_attach,
  'ttf': ZetaIcons.ttf_attach,
  'txt': ZetaIcons.txt_attach,
  'vcf': ZetaIcons.vcf_attach,
  'video': ZetaIcons.video_attach,
  'wav': ZetaIcons.wav_attach,
  'webm': ZetaIcons.webm_attach,
  'wmv': ZetaIcons.wmv_attach,
  'woff': ZetaIcons.woff_attach,
  'xlff': ZetaIcons.xlff_attach,
  'xliff': ZetaIcons.xliff_attach,
  'xls': ZetaIcons.xls_attach,
  'xlsb': ZetaIcons.xlsb_attach,
  'xlsm': ZetaIcons.xlsm_attach,
  'xlsx': ZetaIcons.xlsx_attach,
  'xml': ZetaIcons.xml_attach,
  'xsd': ZetaIcons.xsd_attach,
  'xslt': ZetaIcons.xslt_attach,
  'zip': ZetaIcons.zip_attach,
};
