name: CI - Code Quality
on:
  workflow_call:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{github.event.pull_request.head.repo.full_name}}
          ref: ${{ github.head_ref }}
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - uses: ZebraDevs/flutter-code-quality@v1.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
