name: CI - On Release
on:
  workflow_dispatch:

  push:
    tags:
      - "zeta_*v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  check-package:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: pub.dev
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
          flutter-version: 3.27.x
      - name: Install dependencies
        run: flutter pub get
      - name: Install melos
        run: pub global activate melos
      - name: Check Publish Warnings
        run: melos publish --dry-run
      - name: Publish all
        if: github.ref_name.contains('zeta_flutter') && !github.ref_name.contains('utils') && !github.ref_name.contains('theme') && !github.ref_name.contains('components')
        run: melos publish # --no-dry-run TODO: Uncomment this line to publish
      - name: Publish zeta_flutter (components)
        if: github.ref_name.contains('zeta_flutter_components')
        uses: ./.github/workflows/release-individual-package.yml
        with:
          package: zeta_flutter
      - name: Publish zeta_flutter_theme
        if: github.ref_name.contains('zeta_flutter_theme')
        uses: ./.github/workflows/release-individual-package.yml
        with:
          package: zeta_flutter_theme
      - name: Publish zeta_flutter_utils
        if: github.ref_name.contains('zeta_flutter_utils')
        uses: ./.github/workflows/release-individual-package.yml
        with:
          package: zeta_flutter_utils
      - name: Publish zeta_icons
        if: github.ref_name.contains('zeta_icons')
        uses: ./.github/workflows/release-individual-package.yml
        with:
          package: zeta_icons

  deploy-website:
    runs-on: ubuntu-latest
    needs: check-package
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'zebratechnologies',
              repo: 'zeta',
              workflow_id: 'deploy.yml',
              ref: 'main',
            })
