name: "Merge"

on:
  pull_request:
    types: [closed]

jobs:
  update-version:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
          persist-credentials: false
      - name: Change flutter version tag
        uses: BentEngbers/flutter-change-version@v1.0.3
      - name: push change
        id: update
        run: |
          git remote set-url origin https://${{ secrets.PAT}}@github.com/zebratechnologies/zeta-flutter.git
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit --amend --no-edit
          git push -f

  publish-changelog:
    needs: update-version
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - id: read-version
        uses: NiklasLehnfeld/flutter-version-number-action@main
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{steps.read-version.outputs.version-number}}',
              sha: "${{github.sha}}"
            })
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.PAT }}
          tag: ${{ steps.read-version.outputs.version-number }}
          excludeTypes: ""
          includeInvalidCommits: true
      - name: Make changelog flutter
        run: cp CHANGELOG.md CHANGELOG_FLUTTER.md
      - name: Push changelog to Zeta
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source_file: "CHANGELOG_FLUTTER.md"
          destination_repo: "zebratechnologies/zeta"
          destination_folder: "./"
          destination_branch_create: "flutter/${{ steps.read-version.outputs.version-number }}"
          user_email: "github-actions@github.com"
          user_name: "github-actions"
          commit_message: "flutter changelog"
      - name: Push docs to Zeta
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source_file: "docs/"
          destination_repo: "zebratechnologies/zeta"
          destination_folder: "./docs/flutter"
          destination_branch: "flutter/${{ steps.read-version.outputs.version-number +1}}"
          user_email: "github-actions@github.com"
          user_name: "github-actions"
          commit_message: "flutter docs"
      - name: Open Zeta PR
        uses: thecanadianroot/open-pull-request-action@v1.0.3
        with:
          token: ${{secrets.PAT}}
          base: main
          head: "flutter/${{ steps.read-version.outputs.version-number }}"
          title: "flutter/${{ steps.read-version.outputs.version-number }}"
          labels: flutter
          reviewers: benken
          owner: zebratechnologies
          repository: zebratechnologies/zeta
