name: Up to date
on:
  workflow_call:

jobs:
  up_to_date:
    name: "Check branch is up to date"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Check branch is up to date
        id: check
        run: exit $(gh api /repos/${{github.event.pull_request.head.repo.full_name}}/compare/${{github.event.pull_request.base.sha}}...${{github.event.pull_request.head.sha}} | jq .behind_by)
        env:
          GH_TOKEN: ${{ github.token }}
